# Generated by Django 5.0.6 on 2024-09-02 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='personas.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleadoempresa',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empresa', to='personas.usuario'),
        ),
    ]
