# Generated by Django 5.0.6 on 2024-10-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleadoempresa',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='empleadoempresa',
            name='cargo',
            field=models.CharField(default='Empleado', max_length=100),
        ),
        migrations.AddField(
            model_name='empleadoempresa',
            name='estado',
            field=models.CharField(default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='empleadoempresa',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
