# Generated by Django 5.0.6 on 2024-10-16 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recargausdt',
            name='usuario',
        ),
        migrations.AddField(
            model_name='empresa',
            name='saldo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='recargausdt',
            name='empresa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recargas_usdt', to='personas.empresa'),
        ),
        migrations.AddField(
            model_name='recargausdt',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='recargausdt',
            name='solana_tx_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordendepago',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_pago', to='personas.empleado'),
        ),
        migrations.AlterField(
            model_name='ordendepago',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_pago', to='personas.empresa'),
        ),
    ]
