# Generated by Django 5.0.6 on 2024-09-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_remove_empleado_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PASSPORT', 'Pasaporte'), ('PPT', 'Permiso por Protección Temporal')], max_length=50),
        ),
    ]
