# Generated by Django 5.0.6 on 2024-10-18 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_remove_recargausdt_usuario_empresa_saldo_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='documento_cuenta',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PASSPORT', 'Pasaporte'), ('PPT', 'Permiso por Protección Temporal')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recargausdt',
            name='admin_validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_validadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recargausdt',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprobantedepago',
            name='orden_de_pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='personas.ordendepago'),
        ),
    ]
