# Generated by Django 5.0.6 on 2024-09-25 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_empleado_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='empresas',
        ),
    ]
